# Generated by Django 4.2.7 on 2023-11-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time',
            new_name='time1',
        ),
    ]
